const albums = [
    {sku: 607724, artist: "LED ZEPPELIN", title: "Led Zeppelin 4 (2014 Vinyl Reissue)", releaseDate: "31/10/14", description: 'Released in November 1971, Led Zeppelin IV — which is officially untitled — became one of the most artistically influential and commercially successful albums, one which defined the sound of rock music for a generation with ubiquitous anthems such as "Stairway To Heaven," "Rock And Roll," "Black Dog," and "When The Levee Breaks." The album was inducted into the Grammy Hall of Fame in 1999, has been certified 23x platinum by the RIAA.'},
    {sku: 467948, artist: "LINKIN PARK", title: "Hybrid Theory (Vinyl)", releaseDate: "22/10/13", description: "When the first track from a band's debut album gets added to major rock stations four weeks before its official release, it must be something very special. That's the case with 'One Step Closer' from Linkin Park's first album, 'Hybrid Theory.'"},
    {sku: 361884, artist: "KORN", title: "Issues (JB Hi-Fi Exclusive Turquoise / Clear Vinyl)", releaseDate: "27/11/20", description: ""},
    {sku: 341543, artist: "SYSTEM OF A DOWN", title: "Toxicity (180gm Vinyl) (Reissue)", releaseDate: "12/10/18", description: "The intensity of metal, the social commentary of rap and a plethora of influences – ranging from the band's Armenian heritage to jazz to Middle Eastern melodies to the nightly news – has made System Of A Down an international powerhouse."},
    {sku: 318342, artist: "SLASH", title: "Living The Dream (Vinyl)", releaseDate: "05/10/18", description: "Slash Ft. Myles Kennedy & The Conspirators have announced they'll release their new album titled 'Living The Dream,' via Slash's own label Snakepit Records in partnership with Sony Music Australia!"},
    {sku: 549133, artist: "METALLICA", title: "Master Of Puppets (Vinyl) (Reissue)", releaseDate: "17/11/17", description: "Master of Puppets' is the third studio album by Metallica, originally released on March 3 1986 (last year marked its 30th Anniversary)."},
    {sku: 250782, artist: "AC/DC", title: "High Voltage (Vinyl)", releaseDate: "08/05/09", description: "'High Voltage' is the first internationally released studio album by AC/DC. It contains tracks from their first two previous Australia-only issued albums, 'High Voltage' and 'T.N.T.' (both from 1975)."},
    {sku: 58223, artist: "TOOL", title: "Undertow (Vinyl)", releaseDate: "11/07/04", description: "Arguably their finest album, this follow-up to the 'Opiate' EP showcases Tool at their best, assisted by clean, crisp production, without the muddiness of 'Aenima.' Edgy guitar riffs are complemented by spitting, heavy bass, especially on 'Sober' and 'Crawl Away.'"},
    {sku: 365201, artist: "GUNS N ROSES", title: "Appetite For Destruction (180gm Vinyl) (Reissue)", releaseDate: "27/08/04", description: "'Appetite for Destruction' is the debut studio album by American hard rockers Guns N' Roses."},
    {sku: 539952, artist: "NORTHLANE", title: "Obsidian (JB Hi-Fi AU Exclusive Red Vinyl)", releaseDate: "01/04/22", description: ""},
    {sku: 525373, artist: "PORCUPINE TREE", title: "Incident, The (Vinyl) (Reissue)", releaseDate: "24/09/21", description: ""},
]

export default albums